on: [push]

jobs:
  influxdb_job:
    runs-on: ubuntu-latest
    name: A job to set up InfluxDB
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup InfluxDB
        uses: russorat/influxdb-action@main
        with:
          influxdb_org: organization
          influxdb_user: user
          influxdb_password: password
          influxdb_bucket: bucket
